// src/Publisher/Stubs/Client/Vue/Pages/Welcome.vue
<template>
    <div class="min-h-screen flex items-center justify-center bg-gray-100">
        <div class="bg-white p-8 rounded-lg shadow-lg">
            <h1 class="text-3xl font-bold text-gray-800 mb-4">Welcome to Jengo + Inertia (Vue)</h1>
            <p class="text-gray-600">This is a sample page powered by Vue 3 and CodeIgniter 4.</p>
        </div>
    </div>
</template>

<script setup>
</script>

// src/Publisher/Stubs/Client/React/Pages/Welcome.tsx
import React from 'react';

export default function Welcome() {
    return (
        <div className="min-h-screen flex items-center justify-center bg-gray-100">
            <div className="bg-white p-8 rounded-lg shadow-lg">
                <h1 className="text-3xl font-bold text-gray-800 mb-4">Welcome to Jengo + Inertia (React)</h1>
                <p className="text-gray-600">This is a sample page powered by React and CodeIgniter 4.</p>
            </div>
        </div>
    );
}
